// Auto-generated by generate.py — do not edit by hand.
// Mini bed — 50 x 70 mm ceramic magnets
// Draft 1  |  Eufy E1 UV jig  |  Bambu Lab H2D

$fn = 28;

plate = [318.000, 86.000, 8.000];
base_z = 2.000;
wall = 2.000;
corner_r = 3.000;
pocket_r = 0.800;
pick_r = 4.500;
label = "Mini bed — 50 x 70 mm ceramic magnets";
part_key = "mini-mag-50x70";

pockets = [
    [2.500, 7.750, 50.500, 70.500, 6.000],
    [55.000, 7.750, 50.500, 70.500, 6.000],
    [107.500, 7.750, 50.500, 70.500, 6.000],
    [160.000, 7.750, 50.500, 70.500, 6.000],
    [212.500, 7.750, 50.500, 70.500, 6.000],
    [265.000, 7.750, 50.500, 70.500, 6.000]
];

module rounded_plate(s, r) {
    hull() {
        for (x = [r, s[0] - r])
            for (y = [r, s[1] - r])
                translate([x, y, 0])
                    cylinder(h = s[2], r = r);
    }
}

module rounded_slot(w, h, d, r) {
    rr = min(r, w / 2 - 0.05, h / 2 - 0.05);
    hull() {
        for (x = [rr, w - rr])
            for (y = [rr, h - rr])
                translate([x, y, 0])
                    cylinder(h = d, r = rr);
    }
}

module pick_notches(w, h, d) {
    // Vertical scoop from the top of the wall, stopping 1 mm above the pocket floor.
    if (w >= h) {
        translate([w / 2, 0, 1.0]) cylinder(h = d + 0.4, r = pick_r);
        translate([w / 2, h, 1.0]) cylinder(h = d + 0.4, r = pick_r);
    } else {
        translate([0, h / 2, 1.0]) cylinder(h = d + 0.4, r = pick_r);
        translate([w, h / 2, 1.0]) cylinder(h = d + 0.4, r = pick_r);
    }
}

module jig() {
    difference() {
        rounded_plate(plate, corner_r);
        for (p = pockets) {
            translate([p[0], p[1], base_z]) {
                rounded_slot(p[2], p[3], p[4] + 0.3, pocket_r);
                pick_notches(p[2], p[3], p[4]);
            }
        }
        // Recessed label, top-left unused margin if any, else on the base rim.
        translate([6, plate[1] - 7, plate[2] - 0.6])
            linear_extrude(1)
                text(label, size = 4.2, font = "Arial:style=Bold", valign = "top");
        translate([6, 4.5, plate[2] - 0.6])
            linear_extrude(1)
                text(str(part_key, "  DRAFT 1  LOCK ->"), size = 3.2, font = "Arial", valign = "center");
    }
}

jig();
